print("I tried to make a belt out of watches")
input("")
print("It was a waist of time")
input("-------------")
print("my pencil's tip broke during a test")
input("Now it's pointless")
input("------------")
print("I tried to write a book based on procrastination")
input("I'll finish it tomorrow")