print(">>>What up cuz, Im the JaM, the one and only. I'm the jumper with the greatest jumper, and the best shooter on the court and in the streets.")
name=input(">>>whats your name homie?")
sport=input(f">>>aight {name}, what sport you play")
print(f">>>{sport}? Thats lit, I play basketball, and I'm the best player OAT, thats right, THE GOAT")
print(">>>people talm bout sum LEBRON or MJ, but I would gas any of them 1 on 1")
GOAT=input(">>>Who do you think is the greatest baller of all time")
OneOnOne=input(f"{GOAT}? Thats glaze, but whatever. We gonna 1v1 or nah")
print(f"{OneOnOne}? You think you're better than me? Lets run it {name}. Check up")
input("-----------------------------------------------")
shoot=input("~*He gives you the ball, pumpfake, shoot, ot jab step?*~")
input()
print("~*The JaM slaps the ball out of your hands. TURNOVER*~")
input("HEYYYY, thats too easy! MY ball")
print("~~~~~~Ja's Ball~~~~~~")
input("~*The JaM jabs left but doesn't dribble. Follow his jab or stay still and pre-fire the jumper?*~")
print("~*Ja pulls back from his jab and rises for the shot, but as you jump to block it, he rockets by you and drops the greatest dunk witnessed by man*~")
input(f"~~JA-1~~{name}-0~~")
input("~*The JaM is too nonchalant and humble too talk trash. He steps back and gives you room to shoot, do you shoot or dribble?*~")
print("~*The milisecond your feet show any signs of movement, The JaM enters flowstate and steals the ball before you can even move your wrist.TURNOVER*~")
input("~~~~~~Ja's Ball~~~~~~")
print("~*The goat's beautiful dreads blow in the wind as he aura farms up the court, performing handles only ever envisaged by the gods. He then pulls up from half courts and doesnt even GRACE the rim.*~")
input(f"~~JA-1000000000000000000000000~~{name}-0~~")
print("~*He nonchalantly leaves your presence after sliming some opps, and you realize that his skills are unearthly and only the heavens are worthy witnessing his masterful craft.*~")
